                
management:
  endpoints:
    web:
      exposure:
        include: info,health,messaging                
                
server:
  port: 8380
  
spring:
  profiles:
    # Rabbitmq por default
    active: rabbit

  cloud:
    function:
      routing-expression: headers['type']

    stream:
      function:
        routing:
          enabled: true
      pollable-source: tjf-messaging-error
      
---
######## RABBIT FUNCTION
spring:
  config:
    activate:
      on-profile:
      - rabbit
      
  cloud:
    stream:
      default-binder: rabbit1
      
      bindings:   
        functionRouter-in-0:
          binder: rabbit1
          destination: starship-input
          group: request

    # Filas de Erros
        tjf-messaging-error-in-0:
          destination: bbunit-errors
          group: errors

        tjf-messaging-error-out-0:
          destination: bbunit-errors
          group: errors
          producer:
            required-groups: errors
                       
      binders:
        rabbit1:
          type: rabbit

      rabbit:
        bindings:
          functionRouter-in-0:
            consumer:
              exchange-type: headers
               
---
######## KAFKA
               
spring:
  config:
    activate:
      on-profile:
      - kafka

  cloud:
    stream:
      defaultBinder: kafka1
      bindings:
        starship-input:
          destination: starship-input
          group: requests
        starship-output:
          destination: starship-input
      binders:                
        kafka1:
          type: kafka
                         
      kafka:
        binder:
          brokers: localhost:9092
          configuration:
            auto:
              offset:
                reset: earliest  

---
######## JMS

spring:
  config:
    activate:
      on-profile:
      - jms

  cloud:
    stream:
      defaultBinder: jms1
      bindings:
        functionRouter-in-0:
          binder: jms1
          destination: starship-input
          group: request
      binders:
        jms1:
          type: jms
          environment:
            spring:
              activemq:
                broker-url: tcp://localhost:61616
                user: user-amq
                password: password-amq
