spring:

  cloud:
    stream:
      defaultBinder: rabbit1
      pollable-source: tjf-messaging-error
      
      bindings:
        # Filas de Execução
        bbunit-input:
          destination: bbunit-input
          group: requests
          consumer:
            max-attempts: 1          
        bbunit-output:
          destination: bbunit-input
        
        # Filas de Erros
        tjf-messaging-error-in-0:
          destination: bbunit-errors
          group: errors
        tjf-messaging-error-out-0:
          destination: bbunit-errors
          group: errors
          producer:
            requiredGroups: errors
                      
      binders:
        rabbit1:
          type: rabbit
          environment:
            spring:
              rabbitmq:
                host: localhost
                
management:
  endpoints:
    web:
      exposure:
        include: info,health,messaging
                
server:
  port: 8080
