version: '3'

services:
  postgres:
    image: sameersbn/postgresql:10-1
    restart: always
    environment:
      DB_NAME: communication
      DB_USER: comm
      DB_PASS: totvs@123
      PG_PASSWORD: totvs@123
    ports: 
      - 5432:5432

