tjf:
  api:
    filter:
      fields:
        enabled: true

spring:

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:cash-account;DB_CLOSE_ON_EXIT=FALSE;AUTO_RECONNECT=TRUE;
    username: sa
  
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect

server:
  port: 8380        
