-- Criando tabela droid por causa do ddl-auto não estar funcionando - https://github.com/spring-projects/spring-boot/issues/26609
create table if not exists droid (
    id integer generated by default as identity,
    function varchar(255),
    height double not null,
    name varchar(255),
    primary key (id)
);

INSERT INTO droid (name, function, height) VALUES ('Super Battle Droid', 'Super Soldado de Batalha', 1.91);
INSERT INTO droid (name, function, height) VALUES ('Protocol Droid', 'Auxiliam diplomantas e politicos; Programados em etiqueta e equipados com formidaveis habilidades linguisticas', 1.70);
INSERT INTO droid (name, function, height) VALUES ('Sith Probe Droid', 'Rastrear fugitivos', 0.3);
INSERT INTO droid (name, function, height) VALUES ('Battle Droid' , 'Substituir humanos no campo de batalha, usando a quantidade em seu favor', 1.93);
INSERT INTO droid (name, function, height) VALUES ('Mouse Droid', 'Entregar Mensagens; Guiar Visitantes', 0.25);