-- Criando tabela Jedi por causa do ddl-auto não estar funcionando - https://github.com/spring-projects/spring-boot/issues/26609
create table if not exists jedi (
    id integer generated by default as identity,
    gender varchar(255),
    name varchar(255),
    primary key (id)
);
    
INSERT INTO jedi (id, name, gender) VALUES (1, 'Luke Skywalker', 'male');
INSERT INTO jedi (id, name, gender) VALUES (2, 'Obi-Wan Kenobi', 'male');
INSERT INTO jedi (id, name, gender) VALUES (3, 'Yoda', 'male');
INSERT INTO jedi (id, name, gender) VALUES (4, 'Anakin Skywalker', 'male');
