server:
  port: 8084

spring:
  application:
    name: tjf-messaging-amqp-subscriber
  rabbitmq:
    host: localhost
    username: guest
    password: guest
    
  
tjf:
  messaging:
    amqp:
      security:
         ignore-queue: 
           - starship-queue-1