create table droid_class (
   id integer generated by default as identity,
   name varchar(255),
   primary key (id)
);

create table droid (
   id integer generated by default as identity,
   description varchar(255),
   name varchar(255),
   droid_class integer,
   primary key (id)
);